services:
  api:
    container_name: api
    image: $API_IMAGE_NAME
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT
      - ASPNETCORE_HTTP_PORTS=5000
      - ConnectionStrings__PostgresConnection
      - S3__SpacesKey
      - S3__SpacesSecret
      - StripeApiKey
    volumes:
      - /home/printsev/noizera-data:/noizera-data

  jobs:
    container_name: jobs
    image: $JOBS_IMAGE_NAME
    ports:
      - 5125:5125
    environment:
      - ASPNETCORE_ENVIRONMENT
      - ASPNETCORE_HTTP_PORTS=5125
      - ConnectionStrings__PostgresConnection
    volumes:
      - /home/printsev/noizera-data:/noizera-data
    depends_on:
      - api
      - ffmpeg

  seq:
    container_name: seq
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - /home/printsev/noizera/seq-data:/data
    ports:
      - 5341:5341
      - 8081:80

  reactapp:
    container_name: reactapp
    image: $REACT_IMAGE_NAME
    command: npm start
    ports:
      - 3000:3000
    depends_on:
      - api

  # dashboard:
  #   container_name: dashboard
  #   image: $DASHBOARD_IMAGE_NAME
  #   stop_grace_period: 60s
  #   ports:
  #     - 7000:7000
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT
  #     - ASPNETCORE_HTTP_PORTS=7000
  #   depends_on:
  #     - api

  ffmpeg:
    container_name: ffmpeg
    image: jrottenberg/ffmpeg:latest

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - 5050:5050
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
      - PGADMIN_LISTEN_PORT=5050
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
