version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile

  reactapp:
    build:
      context: ./reactapp

  jobs:
    build:
      context: .
      dockerfile: background-jobs/Dockerfile
