<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net8.0</TargetFramework>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
	  <!--<AnalysisLevel>none</AnalysisLevel>
	  --><!--<AnalysisLevel>latest-Recommended</AnalysisLevel>--><!--
	<AnalysisMode>All</AnalysisMode>
	<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	<CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
	<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>-->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
  </ItemGroup>

</Project>
