<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<!--<AnalysisLevel>none</AnalysisLevel>
	--><!--<AnalysisLevel>latest-Recommended</AnalysisLevel>--><!--
	<AnalysisMode>All</AnalysisMode>
	<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	<CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
	<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>-->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0-preview.6.24327.7" />
    <PackageReference Include="SerilogTracing" Version="2.1.1-dev-00324" />
    <PackageReference Include="SerilogTracing.Expressions" Version="2.1.1-dev-00324" />
    <PackageReference Include="SerilogTracing.Instrumentation.AspNetCore" Version="2.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\shared\src\Noizera.Shared.Contracts\Noizera.Shared.Contracts.csproj" />
  </ItemGroup>

</Project>
