<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<EnableNETAnalyzers>true</EnableNETAnalyzers>
	<AnalysisMode>AllEnabledByDefault</AnalysisMode>
	<AnalysisLevel>latest</AnalysisLevel>
	<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.0" />
    <PackageReference Include="SerilogTracing" Version="2.2.0" />
    <PackageReference Include="SerilogTracing.Expressions" Version="2.2.0" />
    <PackageReference Include="SerilogTracing.Instrumentation.AspNetCore" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\shared\src\Noizera.Common.Contracts\Noizera.Common.Contracts.csproj" />
    <ProjectReference Include="..\..\..\shared\src\Noizera.Common.Persistence\Noizera.Common.Persistence.csproj" />
  </ItemGroup>

</Project>
