// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Noizera.Shared.Persistence.SQL;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Noizera.Shared.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("NumberIdSequence")
                .StartsAt(1000L);

            modelBuilder.Entity("Noizera.Shared.Domain.ListeningHistories.ListeningHistory", b =>
                {
                    b.Property<Guid>("ListenerUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("FirstPlayed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FirstSkipped")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FirstStreamed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastPlayed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSkipped")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastStreamed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ListeningTimeInSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("PlayCount")
                        .HasColumnType("integer");

                    b.Property<int>("SkipCount")
                        .HasColumnType("integer");

                    b.Property<int>("StreamCount")
                        .HasColumnType("integer");

                    b.HasKey("ListenerUserId", "SongId");

                    b.HasIndex("SongId");

                    b.ToTable("ListeningHistories");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.MusicSetCredits.MusicSetCredit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MusicSetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProfileName")
                        .HasColumnType("text");

                    b.Property<int?>("ProfileType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("MusicSetId", "ProfileId")
                        .IsUnique();

                    b.ToTable("MusicSetCredits");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.MusicSetSongs.MusicSetSong", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MusicSetId")
                        .HasColumnType("uuid");

                    b.Property<short>("Sequence")
                        .HasColumnType("smallint");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.HasIndex("MusicSetId", "SongId")
                        .IsUnique();

                    b.ToTable("MusicSetSongs");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.MusicSets.MusicSet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowedAsPreview")
                        .HasColumnType("boolean");

                    b.Property<string>("CollectionType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("CoverImageBucketName")
                        .HasColumnType("text");

                    b.Property<long?>("CoverImageContentLength")
                        .HasColumnType("bigint");

                    b.Property<string>("CoverImageOriginalName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PublicId")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("MusicSets");

                    b.HasDiscriminator<string>("CollectionType").HasValue("collection_base");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Noizera.Shared.Domain.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorText")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("FailedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRealTime")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ProcessAfter")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Retries")
                        .HasColumnType("smallint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.ProfileRelations.ProfileRelation", b =>
                {
                    b.Property<Guid>("FollowerProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FollowingProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("FollowerProfileId", "FollowingProfileId");

                    b.HasIndex("FollowingProfileId");

                    b.ToTable("ProfileRelations");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.Profiles.PublicProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublicId")
                        .HasColumnType("text");

                    b.Property<short>("SongLimitToUpload")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.Royalties.Royalty", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PayeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SongId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PayeeId");

                    b.HasIndex("PayerId");

                    b.HasIndex("SongId");

                    b.ToTable("Royalties");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.SavedMusicSets.SavedMusicSet", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MusicSetId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "MusicSetId");

                    b.HasIndex("MusicSetId");

                    b.ToTable("SavedMusicSets");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.SecretTokens.SecretToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpireAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.SongCredits.SongCredit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("SongId");

                    b.ToTable("SongCredits");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.SongPreferences.SongPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastProcessedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("Value")
                        .HasColumnType("real");

                    b.HasKey("UserId", "SongId");

                    b.ToTable("SongPreferences");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.SongSimilarities.SongSimilarity", b =>
                {
                    b.Property<Guid>("FirstSongId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SecondSongId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastProcessedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("Value")
                        .HasColumnType("real");

                    b.HasKey("FirstSongId", "SecondSongId");

                    b.ToTable("SongSimilarities");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.Songs.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<float?>("BPM")
                        .HasColumnType("real");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("Danceability")
                        .HasColumnType("real");

                    b.Property<double?>("DurationInSeconds")
                        .HasColumnType("double precision");

                    b.Property<float?>("Energy")
                        .HasColumnType("real");

                    b.Property<string>("FlacBucketName")
                        .HasColumnType("text");

                    b.Property<long?>("FlacContentLength")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<char?>("Key")
                        .HasColumnType("character(1)");

                    b.Property<string>("Mp3BucketName")
                        .HasColumnType("text");

                    b.Property<long?>("Mp3ContentLength")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalBucketName")
                        .HasColumnType("text");

                    b.Property<long?>("OriginalContentLength")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalContentType")
                        .HasColumnType("text");

                    b.Property<string>("OriginalFileExtension")
                        .HasColumnType("text");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PublicId")
                        .HasColumnType("text");

                    b.Property<string>("Scale")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.Streams.StreamInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uuid");

                    b.Property<int>("TimeInSeconds")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.HasIndex("UserId");

                    b.ToTable("Streams");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.Subscriptions.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("FreeTrialInDays")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsAnnual")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ProfileTypes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("RoyaltyShare")
                        .HasColumnType("real");

                    b.Property<string>("StripePriceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubscriptionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.Terms.TermsOfUse", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Terms");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.UserSubscriptions.UserSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CancelledOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CheckoutSessionId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CheckoutSessionProcessedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CurrentPeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubscriptionStripeId")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerStripeId")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.VerificationCodes.VerificationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpireAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Invalid")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("VerificationCodes");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.MusicSets.Album", b =>
                {
                    b.HasBaseType("Noizera.Shared.Domain.MusicSets.MusicSet");

                    b.Property<DateOnly?>("AlbumReleaseDate")
                        .HasColumnType("DATE");

                    b.Property<string>("AlbumStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("collection_album");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.MusicSets.Playlist", b =>
                {
                    b.HasBaseType("Noizera.Shared.Domain.MusicSets.MusicSet");

                    b.Property<string>("PlaylistTag")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("collection_playlist");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.ListeningHistories.ListeningHistory", b =>
                {
                    b.HasOne("Noizera.Shared.Domain.Users.User", "Listener")
                        .WithMany("ListeningHistories")
                        .HasForeignKey("ListenerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Noizera.Shared.Domain.Songs.Song", "Song")
                        .WithMany("ListeningHistories")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listener");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.MusicSetCredits.MusicSetCredit", b =>
                {
                    b.HasOne("Noizera.Shared.Domain.MusicSets.MusicSet", "MusicSet")
                        .WithMany("Credits")
                        .HasForeignKey("MusicSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Noizera.Shared.Domain.Profiles.PublicProfile", "Profile")
                        .WithMany("MusicSetCredits")
                        .HasForeignKey("ProfileId");

                    b.Navigation("MusicSet");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.MusicSetSongs.MusicSetSong", b =>
                {
                    b.HasOne("Noizera.Shared.Domain.MusicSets.MusicSet", "MusicSet")
                        .WithMany("MusicSetSongs")
                        .HasForeignKey("MusicSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Noizera.Shared.Domain.Songs.Song", "Song")
                        .WithMany("MusicSetSongs")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MusicSet");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.MusicSets.MusicSet", b =>
                {
                    b.HasOne("Noizera.Shared.Domain.Users.User", "Owner")
                        .WithMany("MusicSets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.ProfileRelations.ProfileRelation", b =>
                {
                    b.HasOne("Noizera.Shared.Domain.Profiles.PublicProfile", "FollowerProfile")
                        .WithMany("Followings")
                        .HasForeignKey("FollowerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Noizera.Shared.Domain.Profiles.PublicProfile", "FollowingProfile")
                        .WithMany("Followers")
                        .HasForeignKey("FollowingProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FollowerProfile");

                    b.Navigation("FollowingProfile");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.Profiles.PublicProfile", b =>
                {
                    b.HasOne("Noizera.Shared.Domain.Users.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("Noizera.Shared.Domain.Profiles.PublicProfile", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.Royalties.Royalty", b =>
                {
                    b.HasOne("Noizera.Shared.Domain.Users.User", "Payee")
                        .WithMany("RoyaltiesSent")
                        .HasForeignKey("PayeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Noizera.Shared.Domain.Users.User", "Payer")
                        .WithMany("RoyaltiesReceived")
                        .HasForeignKey("PayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Noizera.Shared.Domain.Songs.Song", null)
                        .WithMany("AssignedRoyalties")
                        .HasForeignKey("SongId");

                    b.Navigation("Payee");

                    b.Navigation("Payer");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.SavedMusicSets.SavedMusicSet", b =>
                {
                    b.HasOne("Noizera.Shared.Domain.MusicSets.MusicSet", "MusicSet")
                        .WithMany("UserLibraries")
                        .HasForeignKey("MusicSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Noizera.Shared.Domain.Users.User", "User")
                        .WithMany("SavedMusicSets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MusicSet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.SecretTokens.SecretToken", b =>
                {
                    b.HasOne("Noizera.Shared.Domain.Users.User", "User")
                        .WithMany("SecretTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.SongCredits.SongCredit", b =>
                {
                    b.HasOne("Noizera.Shared.Domain.Profiles.PublicProfile", "Profile")
                        .WithMany("SongCredits")
                        .HasForeignKey("ProfileId");

                    b.HasOne("Noizera.Shared.Domain.Songs.Song", "Song")
                        .WithMany("Credits")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.Songs.Song", b =>
                {
                    b.HasOne("Noizera.Shared.Domain.Users.User", "Owner")
                        .WithMany("Songs")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.Streams.StreamInfo", b =>
                {
                    b.HasOne("Noizera.Shared.Domain.Songs.Song", "Song")
                        .WithMany("Streams")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Noizera.Shared.Domain.Users.User", "User")
                        .WithMany("Streams")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.UserSubscriptions.UserSubscription", b =>
                {
                    b.HasOne("Noizera.Shared.Domain.Subscriptions.Subscription", "Subscription")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Noizera.Shared.Domain.Users.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.MusicSets.MusicSet", b =>
                {
                    b.Navigation("Credits");

                    b.Navigation("MusicSetSongs");

                    b.Navigation("UserLibraries");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.Profiles.PublicProfile", b =>
                {
                    b.Navigation("Followers");

                    b.Navigation("Followings");

                    b.Navigation("MusicSetCredits");

                    b.Navigation("SongCredits");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.Songs.Song", b =>
                {
                    b.Navigation("AssignedRoyalties");

                    b.Navigation("Credits");

                    b.Navigation("ListeningHistories");

                    b.Navigation("MusicSetSongs");

                    b.Navigation("Streams");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.Subscriptions.Subscription", b =>
                {
                    b.Navigation("UserSubscriptions");
                });

            modelBuilder.Entity("Noizera.Shared.Domain.Users.User", b =>
                {
                    b.Navigation("ListeningHistories");

                    b.Navigation("MusicSets");

                    b.Navigation("Profile");

                    b.Navigation("RoyaltiesReceived");

                    b.Navigation("RoyaltiesSent");

                    b.Navigation("SavedMusicSets");

                    b.Navigation("SecretTokens");

                    b.Navigation("Songs");

                    b.Navigation("Streams");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
