<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <!--<AnalysisLevel>none</AnalysisLevel>
	  --><!--<AnalysisLevel>latest-Recommended</AnalysisLevel>--><!--
	<AnalysisMode>All</AnalysisMode>
	<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	<CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
	<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>-->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hashids.net" Version="1.7.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\shared\src\Noizera.Shared.Contracts\Noizera.Shared.Contracts.csproj" />
    <ProjectReference Include="..\..\..\shared\src\Noizera.Shared.Infrastructure\Noizera.Shared.Infrastructure.csproj" />
  </ItemGroup>

</Project>
